### ISSUE TITLE
meaningless to add cpu list to measure single cpu power

### ISSUE THREAD

**Issue by hanqf-git** [lixiaobai09/intel_power_consumption_get#2]
msr MSR_RAPL_POWER_UNIT和MSR_PKG_ENERGY_STATUS都是package scode的，也就是一个package只有一个这样的寄存器，package一般就是一个socket, socket内部的所有cpu core/Hthrad共享这一个msr寄存器，分别读每个cpu的MSR_PKG_ENERGY_STATUS值来计算功耗是没有意义的，计算出的是整个package的功耗

**Comment by lixiaobai09** [comment]
你说的是对的，但是对于服务器的NUMA架构之类的，可能还是得需要自己统计下总和。我在README里面说明下吧。
